angular.module('templates.cache', []).run(['$templateCache', function($templateCache) {
  'use strict';
  $templateCache.put('app/views/messages/errorEmail.html',
    '<div ng-message=required class=help-block>Email is required</div><div ng-message=email class=help-block>Email incorect</div>');
  $templateCache.put('app/views/messages/errorFirstName.html',
    '<div ng-message=required class=help-block>firstName is required</div><div ng-message=minlength class=help-block>firstName is to short</div><div ng-message=maxlength class=help-block>firsttName is to long</div>');
  $templateCache.put('app/views/messages/errorLastName.html',
    '<div ng-message=required class=help-block>LastName is required</div><div ng-message=minlength class=help-block>LastName is to short</div><div ng-message=maxlength class=help-block>LastName is to long</div>');
  $templateCache.put('app/views/messages/errorPassword.html',
    '<div ng-message=required class=help-block>Name is required</div><div ng-message=minlength class=help-block>Name is to short</div><div ng-message=maxlength class=help-block>Name is to long</div><div ng-message=confirm class=help-block>Name is to long</div>');
  $templateCache.put('app/views/partials/about.html',
    '');
  $templateCache.put('app/views/partials/admin.html',
    'toto');
  $templateCache.put('app/views/partials/album.html',
    '<div class=container><div class="row marketing"><div class=col-lg-12><a class="btn btn-primary" href=/albums><span class="glyphicon glyphicon-arrow-left"></span></a><h2 class=text-center>{{album.title}}</h2><p class="text-center lead">{{album.description}}</p><div class=text-center><img ng-src="{{API_URL + \'/\' + album.picture}}" width=150px alt="{{album.title | slugify}}"><div class=text-center><small>posté par : {{album.last_name_user}}</small><br><small>{{album.update}}</small></div></div></div></div></div>');
  $templateCache.put('app/views/partials/albums.html',
    '<div class=container><div class=jumbotron><div class="col-xs-3 col-xs-offset-1"><select class=form-control ng-change=check() ng-model=selectAuthor name="" ng-options="genre.first_name + \'\' + author.last_name for genre in authorList._embedded.author"><option value="">Author</option></select></div><div class=col-xs-3><select class=form-control ng-change=check() ng-model=selectGenre name="" ng-options="genre.name for genre in genreList._embedded.genre"><option value="">Genre</option></select></div><div class=col-xs-3><select class=form-control ng-change=check() ng-model=selectType name="" ng-options="type.text for type in typesList.elements"><option value="">Type</option></select></div><div class=col-xs-1><div class="form-control btn btn-danger" ng-click=reset() name=name value=""><span class="glyphicon glyphicon-refresh"></span></div></div><br></div><div class=row dir-loader=albums><div class="col-xs-6 mBop" ng-repeat="album in albums._embedded.albumfull"><h4 class=text-center>{{album.title | characters:35}}</h4><div class=text-center><img class=img-circle ng-src="{{API_URL + \'/\' + album.picture}}" width=150px alt="{{album.title | slugify}}"></div><p class="text-center lead hDesc">{{album.description | characters:30}}</p><div class=text-center><a ng-href=/album/{{album.id}} class="btn btn-primary lead">Read More</a></div></div></div></div>');
  $templateCache.put('app/views/partials/atout.html',
    '<div class=container><div class=col-md-12><h2 class="text-center h2A">LA DOMOTIQUE</h2><p class=text-center>Qu’est ce que c’est ? En quoi va t’elle changer ma vie ?</p></div><div class="col-md-4 text-center atout"><i class="fa fa-lock" aria-hidden=true></i><br><p class=tA>Sécurité</p><p class="pA col-md-8 col-md-offset-2">Des centaines d’euros économisés grace à de simples ajustement automatisé</p></div><div class="col-md-4 text-center atout"><i class="fa fa-bolt" aria-hidden=true></i><p class=tA>Economies</p><p class="col-md-8 col-md-offset-2 pA">Un service client à la hauteur de vos éspérences 24h/24h</p></div><div class="col-md-4 text-center atout"><i class="fa fa-wifi" aria-hidden=true></i><p class=tA>Instalation</p><p class="col-md-8 col-md-offset-2 pA">Une instalation de qualité garantie 1 ans pour tout problème contactez nous</p></div></div>');
  $templateCache.put('app/views/partials/carousel.html',
    '<div id=carousel-example-generic class="carousel slide" data-ride=carousel><ol class=carousel-indicators><li data-target=#carousel-example-generic data-slide-to=0 class=active></li><li data-target=#carousel-example-generic data-slide-to=1></li></ol><div class=carousel-inner role=listbox><div class="item active row vertical-align"><h2 class="col-md-12 text-center vCh"><span class=h2Fk>Franklin</span> Domotique d\'une main tout est automatique</h2><div class=carousel-caption></div></div><div class="item row vertical-align"><h2 class="col-md-12 text-center vCh">test 2</h2><div class=carousel-caption></div></div></div></div>');
  $templateCache.put('app/views/partials/contact.html',
    '<div class="col-md-10 col-md-offset-1"><form class=form-group action=index.html method=post><input class=form-control name=name placeholder=Nom><br><input class=form-control name=name placeholder=Prénom><br><input class=form-control name=name placeholder=Objet><br><textarea class=form-control name=name rows=8 cols=40 placeholder="Entrer votre texte ici"></textarea></form></div>');
  $templateCache.put('app/views/partials/contacts.html',
    '<div class="contacts text-center"><h2 class=h2C>NOUS CONTACTER</h2><h3>Contacter un commercial</h3><p></p></div>');
  $templateCache.put('app/views/partials/devis.html',
    '<div class="text-center devis"><h2 class=h2D>Comment obtenir un devis ?</h2><h3 class=h3D>Obtenez votre devis informatif grâce à notre application en cliquant ici</h3><p></p></div>');
  $templateCache.put('app/views/partials/home.html',
    '<div ng-controller=CarouselCtrl class=header><ng-include src=pathViewCarou></ng-include></div><div ng-controller=AtoutsCtrl class=bg-atout><ng-include src=pathViewAtouts></ng-include></div><div ng-controller=ProduitsCtrl><ng-include src=pathViewProduits></ng-include></div><div ng-controller=DevisCtrl class="devis col-md-6"><ng-include src=pathViewDevis></ng-include></div><div ng-controller=ContactsCtrl class="bg-contact contact col-md-6"><ng-include src=pathViewContacts></ng-include></div>');
  $templateCache.put('app/views/partials/menu.html',
    '<header><nav class="navbar navbar-default" role=navigation><div class=container><div class=navbar-header><button type=button class=navbar-toggle data-toggle=collapse data-target=#bs-example-navbar-collapse-1><span class=sr-only>Toggle navigation</span> <span class=icon-bar></span> <span class=icon-bar></span> <span class=icon-bar></span></button> <a href=# class=navbar-brand><div class=bg-logo></div></a></div><div class="collapse navbar-collapse" id=bs-example-navbar-collapse-1><ul class="nav navbar-nav"><li class=nav-item ng-class="{active:isActive(\'/\')}"><a class=nav-link href="/">ACCUEIL <span class=sr-only>(current)</span></a></li><li class=nav-item ng-class="{active:isActive(\'/albums\')}"><a class=nav-link href=/albums>PRODUITS</a></li><li class=nav-item ng-class="{active:isActive(\'/contact\')}"><a class=nav-link href=/contact>CONTACT</a></li><li class=nav-item ng-class="{active:isActive(\'/about\')}"><a class=nav-link href=/about>QUI SOMMES NOUS ?</a></li></ul><ul class="nav navbar-nav navbar-right"><li class=nav-item ng-show=!isConnected ng-class="{active:isActive(\'/signin\')}"><a class=nav-link href=/signin>CONNEXION</a></li><li ng-show=isConnected><a class=nav-link href=/logout>DECONNEXION : {{userMail}}</a></li></ul></div></div></nav></header>');
  $templateCache.put('app/views/partials/product.html',
    '<div class="product-content col-md-12">produits</div>');
  $templateCache.put('app/views/partials/UserRegister.html',
    '<div class=container><form name=form ng-submit=submit() novalidate><div class=row><div class=col-xs-1><a class="btn btn-primary" href=/signin><span class="glyphicon glyphicon-arrow-left"></span></a></div><div class=col-xs-10><h4 class=text-center>Register</h4></div></div><br><div class=form-group ng-class="{\'has-error\': (submitted || form.firstName.$dirty) && form.firstName.$invalid}"><label for=firstName>firstName</label><input name=firstName id=firstName class=form-control placeholder="First Name" ng-model=inputFirstName required ng-minlength=2 ng-maxlength=25><div ng-show="submitted || form.firstName.$dirty" ng-messages=form.firstName.$error><div ng-messages-include=app/views/messages/errorFirstName.html></div></div></div><div class=form-group ng-class="{\'has-error\': (submitted || form.lastName.$dirty) && form.lastName.$invalid}"><label for=lastName>lastName</label><input name=lastName id=lastName class=form-control placeholder=lastname ng-model=inputLastName ng-minlength=2 ng-maxlength=25 required><div ng-show="submitted || form.lastName.$dirty" ng-messages=form.lastName.$error><div ng-messages-include=app/views/messages/errorLastName.html></div></div></div><div class=form-group ng-class="{\'has-error\': (submitted || form.email.$dirty) && form.email.$invalid}"><label for=email>email</label><input type=email name=email id=email class=form-control placeholder=email ng-model=inputEmail required ng-minlength=2 ng-maxlength=25><div ng-show="submitted || form.email.$dirty" ng-messages=form.email.$error><div ng-messages-include=app/views/messages/errorEmail.html></div></div></div><div class=form-group><label for=password>password</label><input type=password name=password id=password class=form-control placeholder=password ng-model=inputPassword ng-change=checkPassword() required ng-minlength=5 ng-maxlength=25></div><div class=form-group><label for=confirPassword>confirPassword</label><input type=password name=confirPassword id=confirmPassword ng-change=checkPassword() class=form-control placeholder=confirPassword ng-model=inputConfirmPassword required ng-minlength=5 ng-maxlength=25></div><input type=submit name=name class="btn btn-success" value=Envoyé></form></div>');
  $templateCache.put('app/views/partials/UserSignin.html',
    '<div class=container><form name=form ng-submit=submit() novalidate><div class=form-group ng-class="{\'has-error\': (submitted || form.email.$dirty) && form.email.$invalid}"><label for=email>email</label><input type=email name=email id=email class=form-control placeholder=email ng-model=inputEmail required ng-minlength=2 ng-maxlength=25><div ng-show="submitted || form.email.$dirty" ng-messages=form.email.$error><div ng-messages-include=app/views/messages/errorEmail.html></div></div></div><div class=form-group><label for=password>password</label><input type=password name=password id=password class=form-control placeholder=password ng-model=inputPassword ng-change=checkPassword() required ng-minlength=5 ng-maxlength=25></div><input type=submit name=name class="btn btn-success" value=Envoyé> <a class="btn btn-primary" href=/register>Register</a></form></div>');
}]);
